# Generated by Django 2.1.7 on 2019-03-25 23:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=12)),
                ('isActive', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
