# Generated by Django 2.1.7 on 2019-03-25 23:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('used_pins', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RpiBoard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='RpiPinOut',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40)], unique=True)),
                ('function', models.CharField(max_length=20)),
                ('bcm_number', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        migrations.AddField(
            model_name='rpiboard',
            name='available_pins',
            field=models.ManyToManyField(to='rpi.RpiPinOut'),
        ),
        migrations.AddField(
            model_name='rpiboard',
            name='connected_devices',
            field=models.ManyToManyField(through='rpi.Connection', to='device.Device'),
        ),
        migrations.AddField(
            model_name='connection',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpi.RpiBoard'),
        ),
        migrations.AddField(
            model_name='connection',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.Device'),
        ),
    ]
