# Generated by Django 2.1.7 on 2019-03-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpiboard',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
