# Generated by Django 2.1.7 on 2019-03-25 16:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0001_initial'),
        ('rpi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='rpiboard',
            name='motor',
        ),
        migrations.AddField(
            model_name='devices',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpi.RpiBoard'),
        ),
        migrations.AddField(
            model_name='devices',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motor.Motor'),
        ),
        migrations.AddField(
            model_name='rpiboard',
            name='connected_devices',
            field=models.ManyToManyField(through='rpi.Devices', to='motor.Motor'),
        ),
    ]
