# Generated by Django 2.1.7 on 2019-03-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpi', '0002_auto_20190325_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='used_pins',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
