# Generated by Django 2.1.7 on 2019-03-26 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpi', '0002_auto_20190325_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='used_pins',
            field=models.CharField(max_length=50),
        ),
    ]
