# Generated by Django 2.1.7 on 2019-03-22 17:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpi', '0002_rpipinout_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpipinout',
            name='number',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)]),
        ),
    ]
