# Generated by Django 2.1.7 on 2019-03-22 17:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gcode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gcode_file', models.FileField(upload_to='media')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
