# Generated by Django 2.1.7 on 2019-03-25 16:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rpi', '0001_initial'),
        ('motor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gcode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gcode_file', models.FileField(upload_to='media')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=30)),
                ('motors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motor.Motor')),
                ('pi_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpi.RpiBoard')),
            ],
        ),
        migrations.AddField(
            model_name='plot',
            name='settings',
            field=models.ManyToManyField(to='plot.Settings'),
        ),
    ]
