# Generated by Django 2.1.7 on 2019-03-23 17:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('plot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='project_name',
            field=models.CharField(default='Plot', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='settings',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
