# Generated by Django 2.1.7 on 2019-03-26 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='name',
            field=models.CharField(default='Plotting CNC', max_length=30),
            preserve_default=False,
        ),
    ]
