# Generated by Django 2.1.7 on 2019-03-26 01:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plot', '0002_plot_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
