# Generated by Django 2.1.7 on 2019-03-21 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plot', '0002_rpiconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RpiConfig',
        ),
    ]
