# Generated by Django 2.1.7 on 2019-03-25 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpi', '0003_devices_used_pins'),
        ('plot', '0002_remove_plot_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='motors',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='pi_board',
        ),
        migrations.AddField(
            model_name='plot',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rpi.Devices'),
        ),
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
