# Generated by Django 2.1.7 on 2019-03-26 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpi', '0003_auto_20190326_0007'),
        ('plot', '0003_plot_create_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plot',
            unique_together={('name', 'board')},
        ),
    ]
