# Generated by Django 2.1.7 on 2019-03-21 16:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motor',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 3, 21, 16, 52, 22, 651250, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
